name: docker-build
on: [release]
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Get release tag
          id: tag
          run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        - uses: actions/checkout@master
        - name: Log in to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Build and Push Docker Image
          uses: docker/build-push-action@v4
          with:
            context: .
            push: true
            tags: ghcr.io/anuaimi/rgeosrv:latest
